name: Deploy to Google Cloud Artifact Registry

on:
  push:
    branches:
      - master # O la rama que prefieras para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # O la versión de Python que utilices

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > ${{ github.workspace }}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set run/region ${{ secrets.REGION }}

      - name: Push Docker image to Google Cloud Artifact Registry
        run: |
          docker tag gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.IMAGE_NAME }}:latest gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Deploy to Google Cloud Run (optional)
        run: |
          gcloud run deploy my-service --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.IMAGE_NAME }}:latest --platform managed --region ${{ secrets.REGION }} --allow-unauthenticated
