name: Deploy to Google Cloud

on:
  push:
    branches:
      - master # O la rama que prefieras para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > ${{ github.workspace }}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --region=${{ secrets.REGION }} --tag ${{secrets.RUTE_REPO}}/${{ secrets.NAME_ARTIFACT }}:${{ secrets.TAG_DEPLOY }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy --image=${{ secrets.RUTE_IMAGE }}:${{ secrets.TAG_DEPLOY }}
